// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: errors/error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义当前请求的状态
type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// http 状态码, 比如 200, 204, 301, 302, 400, 403, 500, 504 等等
	HttpCode int32 `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"-"` // @inject_tag: json:"-"
	// 业务错误代码, 由业务定义的业务错误代码 比如说业务定义 10000 表示请求成功
	ErrNo int64 `protobuf:"varint,2,opt,name=err_no,json=errNo,proto3" json:"err_no"` // @inject_tag: json:"err_no"
	// 业务错误消息提示,  比如业务定义 success 表示请求成功
	ErrMsg string `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg"` // @inject_tag: json:"err_msg"
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_errors_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_errors_error_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetHttpCode() int32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

func (x *Status) GetErrNo() int64 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *Status) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_errors_error_proto protoreflect.FileDescriptor

var file_errors_error_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x22, 0x55, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6c, 0x6d, 0x75, 0x7a, 0x2f, 0x69,
	0x6a, 0x6b, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x3b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errors_error_proto_rawDescOnce sync.Once
	file_errors_error_proto_rawDescData = file_errors_error_proto_rawDesc
)

func file_errors_error_proto_rawDescGZIP() []byte {
	file_errors_error_proto_rawDescOnce.Do(func() {
		file_errors_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_error_proto_rawDescData)
	})
	return file_errors_error_proto_rawDescData
}

var file_errors_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_error_proto_goTypes = []interface{}{
	(*Status)(nil), // 0: errors.errors.Status
}
var file_errors_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_error_proto_init() }
func file_errors_error_proto_init() {
	if File_errors_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_errors_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_error_proto_goTypes,
		DependencyIndexes: file_errors_error_proto_depIdxs,
		MessageInfos:      file_errors_error_proto_msgTypes,
	}.Build()
	File_errors_error_proto = out.File
	file_errors_error_proto_rawDesc = nil
	file_errors_error_proto_goTypes = nil
	file_errors_error_proto_depIdxs = nil
}
